// front-end-angular/src/app/features/dashboard/dashboard.ts
import { Component, inject, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthStore } from '../auth/auth.store';

import { AdminDashboard } from './admin-dashboard';
import { WorkerDashboard } from './worker-dashboard';

@Component({
  selector: 'dashboard-proxy',
  standalone: true,
  imports: [CommonModule, AdminDashboard, WorkerDashboard],
  template: `
    @if (role() === 'admin') {
      <admin-dashboard />
    } @else {
      <worker-dashboard />
    }
  `
})
export class Dashboard {
  private auth = inject(AuthStore);

  role = computed(() => this.auth.user()?.role);
}

// front-end-react/src/features/dashboard/components/Dashboard.jsx
import { useSelector } from "react-redux";
import AdminDashboard from "./AdminDashboard.jsx";
import WorkerDashboard from "./WorkerDashboard.jsx";

const StaffDashboard = () => {
  const user = useSelector((s) => s.auth.user);
  const role = user?.role;

  if (role === "admin") return <AdminDashboard />;
  if (role === "worker") return <WorkerDashboard />;

  return null;
}

export default StaffDashboard;
